api_platform:
    title: Pizza API
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    formats:
        json:
            mime_types: [ 'application/json' ]
        jsonapi:
            mime_types: [ 'application/vnd.api+json' ]
        jsonld:
            mime_types: [ 'application/ld+json' ]
        html:
            mime_types: [ 'text/html' ]
        form-data:
            mime_types: [ 'multipart/form-data' ]
    collection:
        pagination:
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: limit # Default value
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
#    # Mercure integration, remove if unwanted
#    mercure:
#        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    # Good defaults value for REST APIs
    defaults:
        stateless: true
        pagination_items_per_page: 10
        # Good cache defaults
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        route_prefix: '/api'
    
